### ISSUE TITLE
f-droid release

### ISSUE THREAD

**Issue by c33s** [warren-bank/Android-Tiny-Television-Time-Tracker#3]
as the orginal author from droidshow references this project as replacement a release on f-droid would be awesome.

**Comment by ltguillaume** [comment]
DroidShows author here.

Well, TheTVDB has fixed their issues with the legacy API, it seems, so DroidShows should be working again. I'd still say this project here would be a great fit for new users, because using TMDb is a better choice either way.

I removed the migration instructions, though, because I can't recommend a database migration that has such a severe impact on flash memory as this one.

**Comment by c33s** [comment]
so do you think about adding your app to f-droid?

sidequestion: what about the jar file to do the migration on the desktop? will you release that somewhere?

**Comment by jmichael2497** [comment]
~~was hoping to see this in f-droid (or an update) since the api issue is back in the parent app and maybe finally time to spread the word about this fork.~~

edit: sorry false alarm on my part, after refreshing and spot checks of the others that had trouble last time, it looks like just season numbering conflict of opinion by recent editor of single series at TVDB, similar but reverse at TMDB, only TVmaze has the finished thought, my apologies for jumping to conclusions.

**Comment by Ibuprophen** [comment]
I believe @ltguillaume did something like a post announcement on his XDA thread. 

I was just wondering if ltguillaume planned to merge this fork to his repository and add Warren to it as another Administrative Developer to the Repository. I kinda like the app name Droid Shows myself. 

Just a personal opinion/suggestion. 👍

~Ibuprophen

**Comment by jmichael2497** [comment]
nvm, i was too hasty, just incomplete source edits.
